[project]
name = "MoMaMotiveLink"
version = "0.2.8"
description = "Module for MoMa Motive Link integration"
requires-python = "~=3.13.0"
dependencies = [
    "natnet>=0.2.0",
    "numpy>=1.24.0",
]

[tool.uv.sources]
natnet = { git = "https://github.com/TimSchneider42/python-natnet-client.git" }

