[project]
name = "MoMaMotiveLink"
version = "0.2.9"
description = "Module for MoMa Motive Link integration"
requires-python = "~=3.13.0"
dependencies = [
    "numpy>=1.24.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.2",
]

